<script setup lang="ts"></script>

<template>
  <div class="container">
    <h1 class="title__big">ITPR</h1>
    <h2 class="title__subtitle">Is this person real?</h2>
    <p class="title__text">
      Can you guess which person is real, and which person was generated by an
      AI?
    </p>
  </div>
</template>

<style scoped>
.container {
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.title__big {
  font-weight: 200;
  font-size: 8rem;
  line-height: 1.2;
}

.title__subtitle {
  font-weight: 200;
  font-size: 1.5rem;
  margin-bottom: 3rem;
}

.title__text {
  max-width: 19rem;
}
</style>
