<script setup lang="ts">
import ButtonGeneric from "./ButtonGeneric.vue";
</script>

<template>
  <div class="bg-image"></div>
  <div class="container">
    <h1 class="title__big">ITPR</h1>
    <h2 class="title__subtitle">Is this person real?</h2>
    <p class="title__text">
      Can you guess which person is real, and which person was generated by an
      AI?
    </p>
    <ButtonGeneric class="green">Start Game</ButtonGeneric>
  </div>
</template>

<style scoped>
.container {
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  backdrop-filter: blur(2px);
}

.container > :last-child {
  margin-bottom: 10%;
}

[class^="title"] {
  color: var(--color-white);
  text-align: center;
}

.title__big {
  font-weight: 200;
  font-size: 8rem;
  line-height: 1.2;
}

.title__subtitle {
  font-weight: 200;
  font-size: 1.5rem;
  letter-spacing: 0.05rem;
  margin-bottom: 3rem;
}

.title__text {
  max-width: 16rem;
  margin-bottom: 3.5rem;
}
</style>
