<script setup lang="ts">
import AppButton from "../components/AppButton.vue";
</script>

<template>
  <div class="bg-image"></div>
  <div class="container">
    <h1 class="title__big">ITPR</h1>
    <h2 class="title__subtitle">Is this person real?</h2>
    <p class="title__text">
      Can you guess if the person in an image is real, or if the image was
      generated by an AI?
    </p>
    <AppButton id="title-btn" class="green">Start Game</AppButton>
  </div>
</template>

<style scoped>
@import "@/assets/animation.css";

.container {
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  backdrop-filter: blur(2px);
  overflow: hidden;
}

.container > :last-child {
  margin-bottom: 10%;
}

[class^="title"] {
  color: var(--color-white);
  animation: slideInLeft 1s 0.5s backwards;
}

.title__big {
  font-weight: 200;
  font-size: 8rem;
  line-height: 1.2;
}

.title__subtitle {
  font-weight: 200;
  font-size: 1.5rem;
  letter-spacing: 0.05rem;
  margin-bottom: 3rem;
}

.title__text {
  max-width: 18rem;
  margin-bottom: 3.5rem;
}

#title-btn {
  animation: slideInBottom 1s 1s backwards;
}
</style>
